### ISSUE TITLE
Initial meetup

### ISSUE THREAD

**Issue by katexochen** [nix-community-bochum/nix-learning-group#1]
Planing of the initial meeting can happen in this issue.

Date: `19.10.2023`

# Concept

- Be beginner-friendly
  - Nix pills is a good entry tutorial
  - NixOS live sticks
  - Installing nix on other distros with DS-installer
- Focus on hacking together instead of doing frontal presentations
- People should do 2-5 min presentation to tell others what they are hacking on
  -  Find people to join
  - Start conversations

## Schedule

`17:30` Start / Room available
`18:00` Opening / Concept presentation
`18:10` Nix/NixOS introduction
`  ...  ` Hacking time
`22:00` End

## TODOs

- [x] Funding for food + drinks https://github.com/NixOS/foundation/issues/100
- [x] Create registration form
- [x] Create digital flyer (deadline 5.10.)
- [x] Write announcement text (deadline 5.10.)
- [x] Send flyer + announcement to FSR ITS  (starting 5.10.)
- [x] [Add discourse event](https://discourse.nixos.org/t/nix-os-user-learning-group-bochum-10-19-2023/33887)
- [x] [Add to discourse community calendar](https://discourse.nixos.org/t/community-calendar/18589/87) (@msanft)
- [x] Invite edgelesssys folks (@katexochen)
- [x] Post in [nixos-de matrix room](https://app.element.io/#/room/#de:nixos.org)
- [x] ~Publish on masto/twitter~
- [x] Date for the next meetup 
- [x] Check where to order Pizza (invoice required) (deadline 17.10.)
- [x] Organize drinks (@msanft, deadline 18.10.)
- [x] Prepare short talk meetup concept and structure (@katexochen, deadline 19.10.)
- [x] Prepare short talk introduction to Nix/NixOS (@msanft, deadline 19.10.)
- [x] [Get money back](https://opencollective.com/nixos/expenses/167601)

**Comment by katexochen** [comment]
## Announcement text draft

### Was ist Nix?

Nix ist ein Package Manager, mit dem du Software deklarativ, hermetisch und reproduzierbar bauen kannst. Die Software Pakete werden dafür in der funktionalen Programmiersprache Nix beschrieben. NixOS ist eine Linux Distirbution, die auf Nix aufbaut. Das ganze System wird deklarativ in einer Config beschrieben und lässt sich z.B. einfach reproduzieren oder in Git verwalten. Dabei bricht Nix mit etablierten Linux-Konzepten und eignet sich ideal, um sein Verständnis für Linux und Software generell zu vertiefen.
Mehr Informationen zu Nix/NixOS unter https://nixos.org/.

### Learning Group?

In regelmäßigen Treffen wollen wir mit euch zusammen unser Wissen in Nix vertiefen, zusammen an Systemkonfigurationen hacken und Software packagen. Explizit wollen wir auch Menschen ansprechen, die Nix noch nicht kennen aber gerne ausprobieren würden und euch beim Einstig unterstützen.

### Was mitbringen?

Bring am besten einen Laptop mit Linux mit. Alternativ könnt ihr auch einen bootbaren USB-Stick mitbringen, oder euch eine VM aufsetzen. Wir helfen euch natürlich gerne, Nix/NixOS auf was auch immer ihr mitbringt zu installieren.

### Pizza?

Pizza! Und Getränke. Sag uns vorher am besten Bescheid, dass du planst zu kommen.

**Comment by katexochen** [comment]
Registration Form: https://forms.gle/Ts9cZukpupb2MyUL9

**Comment by katexochen** [comment]
We had 30 registrations, 26 person at the event, 13,3% of registrations didn't come.
