### ISSUE TITLE
Meetup: 2023-11-16

### ISSUE THREAD

**Issue by katexochen** [nix-community-bochum/nix-learning-group#13]
Planing of the initial meeting can happen in this issue.

Date: `16.11.2023`
Location: `RUB, MC 1.30/1.31`

## Schedule

`17:30` Start / Room available
`18:10` Opening / Concept presentation
`18:15` 5min presentations
`  ...  ` Hacking time
`22:00` End

## TODOs

- [x] Funding for food + drinks (FSR ITS)
- [x] Create registration form (@katexochen)
- [x] Create digital flyer (@katexochen, deadline 2.11.)
- [x] Write announcement text (deadline 2.11.)
- [x] Send flyer + announcement to FSR ITS  (starting 2.11.)
- [x] [Add discourse event](https://discourse.nixos.org/t/nix-os-user-learning-group-bochum-11-16-2023/35278) (@msanft)
- [x] [Add to discourse community calendar](https://discourse.nixos.org/t/community-calendar/18589/92) (@msanft)
- [x] Invite edgelesssys folks (@katexochen)
- [x] Invite fluxfingers folks (@msanft)
- [x] Post in [nixos-de matrix room](https://app.element.io/#/room/#de:nixos.org)
- [x] Post in [bochum:nixos.org matrix room](https://app.element.io/#/room/#bochum:nixos.org)
- [x] Publish on masto/twitter
- [x] Date for the next meetup 
- [x] Check where to order Pizza (VAT invoice required) (deadline 14.11.)
- [x] Organize drinks (deadline 15.11.) (@msanft)
- [x] Ping people for short presentations
- [x] Get money back.

**Comment by katexochen** [comment]
Form URL: https://forms.gle/xwY9Tu5LxCrb79wD6

**Comment by katexochen** [comment]
We had 15 registrations, 22 person at the event, 46% more than registered.
