### ISSUE TITLE
Meetup 2024-01-18

### ISSUE THREAD

**Issue by katexochen** [nix-community-bochum/nix-learning-group#18]
Planing of the initial meeting can happen in this issue.

Date: `18.01.2024`
Location: `RUB, MC 1.30/1.31`

## Schedule

`17:30` Start / Room available
`18:10` Opening / Concept presentation
`18:15` 5min presentations
`  ...  ` Hacking time
`22:00` End

## TODOs

- [x] Funding for food + drinks (@msanft)
- [x] Create registration form (@katexochen)
- [x] Create digital flyer (@katexochen, deadline 4th Jan)
- [x] Write announcement text ( , deadline 4th Jan)
- [x] Send flyer + announcement to FSR ITS  (starting 4th Jan)
- [x] [Add discourse event](https://discourse.nixos.org/t/nix-os-user-learning-group-bochum-01-18-2024/37695) (@msanft )
- [x] [Add to discourse community calendar](https://discourse.nixos.org/t/community-calendar/18589/109) (@msanft )
- [x] Invite edgelesssys folks (@katexochen)
- [x] Invite fluxfingers folks (@msanft)
- [ ] Post in [nixos-de matrix room](https://app.element.io/#/room/#de:nixos.org)
- [x] Post in [bochum:nixos.org matrix room](https://app.element.io/#/room/#bochum:nixos.org)
- [x] Publish on masto/twitter
- [x] Post on [Discord: DeterminateSystems.nix-events](https://discord.gg/hpmSRtAc)
- [x] Post on [Discord: Nix/NixOS.conferences-meetups-camps](https://discord.gg/y6dQ3tbt)
- [x] Date for the next meetup 
- [x] Check where to order Pizza (VAT invoice required) (@msanft) -> Falcone
- [x] Organize drinks (@msanft)
- [x] Ping people for short presentations
- [x] Get money back.

**Comment by katexochen** [comment]
registration form: https://forms.gle/Hycs1rzg1q9hUv6G9

**Comment by libnewton** [comment]
ich würde dann die announcements für FSR und AStA machen, wenn ihr ready seid

würde ggf den matrix room verlinken für rückfragen?

**Comment by katexochen** [comment]
@libnewton wir sind ready, announcement und flyer sind hier: https://github.com/nix-community-bochum/nix-learning-group/tree/main/meetups/2024-01-18
