### ISSUE TITLE
Meetup 2024-02-22

### ISSUE THREAD

**Issue by katexochen** [nix-community-bochum/nix-learning-group#23]
Planing of the initial meeting can happen in this issue.

Date: `22.02.2024`
Location: `RUB, MC 1.30/1.31`

## Schedule

`17:30` Start / Room available
`18:10` Opening / Concept presentation
`18:15` 5min presentations
`  ...  ` Hacking time
`22:00` End

## TODOs

- [x] Funding for food + drinks https://github.com/NixOS/foundation/issues/116 (@katexochen)
- [x] Create registration form (@katexochen )
- [x] Create digital flyer (@katexochen, deadline 8th Feb)
- [x] Write announcement text ( , deadline 8th Feb)
- [x] Send flyer + announcement to FSR ITS  (starting 8th Feb)
- [x] [Add discourse event](https://discourse.nixos.org/t/nix-os-user-learning-group-bochum-01-18-2024/37695) (@msanft)
- [x] [Add to discourse community calendar](https://discourse.nixos.org/t/community-calendar/18589/109) (@msanft)
- [x] Invite edgelesssys folks (@katexochen)
- [x] Invite fluxfingers folks (@msanft)
- [ ] Post in [nixos-de matrix room](https://app.element.io/#/room/#de:nixos.org)
- [x] Post in [bochum:nixos.org matrix room](https://app.element.io/#/room/#bochum:nixos.org)
- [x] Publish on masto/twitter
- [ ] Post on [Discord: DeterminateSystems.nix-events](https://discord.gg/hpmSRtAc)
- [ ] Post on [Discord: Nix/NixOS.conferences-meetups-camps](https://discord.gg/y6dQ3tbt)
- [x] Date for the next meetup 
- [x] Check where to order Pizza (VAT invoice required) -> Falcone
- [x] Organize drinks (@msanft)
- [x] Ping people for short presentations
- [x] Get money back: https://opencollective.com/nixos/expenses/189376 @msanft

**Comment by katexochen** [comment]
Registration form: https://forms.gle/wdpdYsaTEZpzWMfV7

**Comment by Freax13** [comment]
![image](https://github.com/nix-community-bochum/nix-learning-group/assets/14952658/96488724-9eec-401a-a2d5-a937cfa033d6)
EDIT: Works now.

**Comment by katexochen** [comment]
@Freax13 you're just too fast xD registration is now open.

**Comment by blipp** [comment]
> Registration form: https://forms.gle/wdpdYsaTEZpzWMfV7

At the bottom, the form still links to the issue for the previous event (January 18):

> Das Event ist community-organized. Damit es richtig gut wird brauchen wir dich!
> Schau auf der [Orga-Seite für das kommende Treffen](https://github.com/nix-community-bochum/nix-learning-group/issues/18), wo noch Hilfe gebraucht wird.
> Wenn du einen kurzen (2-5 min) Talk halten möchtest melde dich bitte dort.

**Comment by katexochen** [comment]
@blipp Thanks, fixed!
