### ISSUE TITLE
Meetup 2024-03-21

### ISSUE THREAD

**Issue by msanft** [nix-community-bochum/nix-learning-group#25]
Planing of the meeting can happen in this issue.

Date: `21.03.2024`
Location: `RUB, MC 1.30/1.31`

## Schedule

`17:30` Start / Room available
`18:10` Opening / Concept presentation
`18:15` 5min presentations
`  ...  ` Hacking time
`22:00` End

## TODOs

- [x] Funding for food + drinks 
- [x] Create registration form 
- [x] Create digital flyer (deadline 8th March)
- [x] Write announcement text ( deadline 8th March)
- [x] Send flyer + announcement to FSR ITS  (starting 8th March)
- [ ] Add discourse event
- [ ] Add to discourse community calendar
- [x] Invite edgelesssys folks 
- [ ] Invite fluxfingers folks (@msanft)
- [ ] Post in [nixos-de matrix room](https://app.element.io/#/room/#de:nixos.org)
- [x] Post in [bochum:nixos.org matrix room](https://app.element.io/#/room/#bochum:nixos.org)
- [ ] Publish on masto/twitter
- [ ] Post on [Discord: DeterminateSystems.nix-events](https://discord.gg/hpmSRtAc)
- [ ] Post on [Discord: Nix/NixOS.conferences-meetups-camps](https://discord.gg/y6dQ3tbt)
- [ ] Date for the next meetup 
- [x] Check where to order Pizza (VAT invoice required) -> Falcone
- [x] Organize drinks 
- [ ] Ping people for short presentations
- [x] Get money back
