### ISSUE TITLE
Meetup 2024-05-14

### ISSUE THREAD

**Issue by katexochen** [nix-community-bochum/nix-learning-group#29]
Planing of the meeting can happen in this issue.

Date: `14.05.2024`
Location: [`Das Labor Bochum, Allestr. 50`](https://wiki.das-labor.org/w/LABOR_Wiki)

## Schedule

`18:00` Start / Room available
`18:10` Opening / Concept presentation
`18:15` 5min presentations
`  ...  ` Hacking time
`22:00` End

## TODOs

- [ ] Funding for food + drinks
- [x] Create digital flyer
- [x] [Add discourse event](https://discourse.nixos.org/t/nix-os-user-learning-group-bochum-05-14-2024/45061)
- [x] [Add to discourse community calendar](https://discourse.nixos.org/t/community-calendar/18589/136)
- [x] Invite edgelesssys folks 
- [x] Invite fluxfingers folks (@msanft)
- [ ] Post in [nixos-de matrix room](https://app.element.io/#/room/#de:nixos.org)
- [x] Post in [bochum:nixos.org matrix room](https://app.element.io/#/room/#bochum:nixos.org)
- [x] Publish on masto/twitter
- [ ] Post on [Discord: DeterminateSystems.nix-events](https://discord.gg/hpmSRtAc)
- [ ] Post on [Discord: Nix/NixOS.conferences-meetups-camps](https://discord.gg/y6dQ3tbt)
- [x] Date for the next meetup 
- [ ] Check where to order Pizza (VAT invoice required) -> Falcone
- [x] Organize drinks (present at Labor)
- [ ] Ping people for short presentations
- [ ] Get money back
